---
kind: List
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: $SERVICE_NAME
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    template:
      metadata:
        labels:
          app: $SERVICE_NAME
          tier: $TIER
          track: $CLUSTER_NAME
        name: $SERVICE_NAME
      spec:
        containers:
        - name: $SERVICE_NAME
          image: $DOCKER_REGISTRY_URL/$SERVICE_NAME:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_ENV
            value: $CLUSTER_NAME
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: TRACK
            value: $CLUSTER_NAME
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: url
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          ports:
          - containerPort: 8080

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: $SERVICE_NAME
      tier: $TIER
      track: $CLUSTER_NAME
    name: $SERVICE_NAME
  spec:
    ports:
    - port: 80
      targetPort: 8080
    selector:
      app: $SERVICE_NAME
